INSERT INTO category (name, description, picture_file_name)
VALUES ('dania arabskie', 'kuchnia arabska obejmuje potrawy pochodzące z krajów świata arabskiego i w każdym z tych regionów znacznie się różni. Wspólnymi elementami są: upodobanie do warzyw (bakłażan, pomidory, papryka, cukinia, pietruszka, cebula, czosnek), owoców (granaty, cytryny, figi), ziół i przypraw, ryżu, kasz (unika się ziemniaków) oraz roślin strączkowych, zwłaszcza ciecierzycy i soczewicy. Najpopularniejszymi daniami lub dodatkami do dań są m.in.: hummus, falafel, zupa harira, tabouleh. Kuchnia krajów pustynnych (bliskowschodnich) opiera się na daniach z baraniny, zaś kuchnia arabska krajów śródziemnomorskich (Liban, Tunezja, Algieria, Maroko) bazuje na warzywach, rybach i owocach. Istotnym uzupełnieniem dań jest pieczywo (sezamowe obwarzanki, podpłomyk, pita).', 'arabic.jpg'),
       ('dania azjatyckie', 'Kuchnia azjatycka cieszy się w Polsce coraz większą popularnością. Wyraziste w smaku dania zawierające regionalne przyprawy, powstałe na bazie charakterystycznych dla tej części świata produktów, takich jak ryż, ryby, owoce morza czy różnego rodzaju sosy, są podstawą tradycyjnej kuchni Azjatów. Mimo wielu cech wspólnych łatwo znaleźć różnice między stylami poszczególnych kuchni składających się na kuchnię azjatycką. Każda z kuchni azjatyckich, tj. kuchnia chińska, indyjska, japońska, wietnamska czy też koreańska, ma swój charakter, wykorzystuje typowe dla danego regionu przyprawy i składniki, dzięki czemu potrawy zyskują na indywidualności, a tym samym wyróżniają kuchnie poszczególnych krajów.', 'asian.png'),
       ('dania meksykańskie', ' sztuka kulinarna Meksyku i okolic, łącząca tradycje tubylczych Indian i wpływów konkwistadorów. Opiera się głównie na kukurydzy i roślinach strączkowych (około 20 różnych gatunków fasoli) i różnych odmianach papryki chili. Kuchnię meksykańską dzieli się ze względu na jej zróżnicowanie regionalne, tj. północną, zachodnią, znad Zatoki, a także z terenów centralnych, gdzie wyróżnia się kuchnię z Bajio, z Aguascalientes, michoacańską oraz kuchnię z Tlaxcali.', 'mexico.jpg');
INSERT INTO recipe (name, number_of_likes, category_id, description, picture_file_name)
VALUES ('Falafel', 0L, 1L, 'Smażone w głębokim tłuszczu kulki lub kotleciki ze zmielonej, wcześniej namoczonej ciecierzycy, doprawionej czosnkiem, natką, kolendrą i kuminem. Popularna wegańska potrawa w krajach arabskich. Lubiana na całym świecie, szczególnie jako street food i roślinna alternatywa kebabu. Namoczoną ciecierzycę najlepiej zmiksować w melakserze. Idealny falafel jest z zewnątrz chrupiący, w środku natomiast miękki. Taki właśnie otrzymamy z poniższego przepisu.', 'falafel.jpg'),
       ('Hummus', 0L, 1L, 'Pasta z ugotowanej ciecierzy z sezamem i czosnkiem.', 'hummus.jpg'),
       ('Sajgonki', 0L, 2L, 'Można je przygotować z podsmażanego wcześniej mięsa (farszu) lub z surowego mięsa i surowych warzyw. Te drugie są oryginalnymi sajgonkami jak z wietnamskiej restauracji, tylko wymagają smażenia w głębszym tłuszczu i trochę dłużej. Natomiast sajgonki z gotowego farszu nieco ciężej się zwija a po usmażeniu farsz nie jest zbity tylko trochę sypki. Ich zaletą jest to, że wystarczy je tylko krótko obsmażyć.', 'spring-rolls.jpg'),
       ('Sushi', 0L, 2L, 'Potrawa japońska złożona z gotowanego ryżu zaprawionego octem ryżowym (su) oraz różnych dodatków w postaci, przeważnie surowych: owoców morza, wodorostów nori, kawałków ryb, warzyw, grzybów, a także omletu japońskiego (tamago-yaki), tofu, ziarna sezamowego (goma). Ze względu na bardzo krótki termin przydatności do spożycia, w restauracjach japońskich jest przygotowywana po dokonaniu zamówienia.', 'sushi.jpg'),
       ('Chili con carne', 0L, 3L, 'tradycyjna potrawa kuchni teksańskiej, spotykana często jako fastfood w amerykańskich barach. Główne składniki to: różnego rodzaju papryka chili, cebula, czosnek, pomidory i mielone lub drobno siekane mięso (zwykle wołowina, czasem spotyka się inne). Potrawę przyprawia się za pomocą kminu rzymskiego (kuminu) i pieprzu. Często dodaje się też inne składniki w tym ziarna fasoli i kukurydzy.', 'chili-con-carne.jpg'),
       ('Guacamole', 0L, 3L, 'Meksykański sos (salsa) przyrządzany na bazie awokado. Guacamole swoje początki miał już w czasach azteckich. Oprócz awokado dodaje się także limonkę i sól. Poszczególne rodzaje guacamole mogą zawierać pomidory, paprykę chili, cebulę, kolendrę, czosnek i inne przyprawy. Spożywa się go zazwyczaj z plackami tortilla, chociaż Meksykanie dodają go do niemal każdej przystawki.', 'guacamole.jpg');
