INSERT INTO category (name, description, picture_file_name)
VALUES ('dania arabskie', 'opis1', 'arabic.jpg'),
       ('dania azjatyckie', 'opis2', 'asian.jpg'),
       ('dania meksykańskie', 'opis3', 'mexico.jpg');
INSERT INTO recipe (name, number_of_likes, category_id, description, picture_file_name)
VALUES ('Falafel', 0L, 1L, 'Smażone w głębokim tłuszczu kulki lub kotleciki ze zmielonej, wcześniej namoczonej ciecierzycy, doprawionej czosnkiem, natką, kolendrą i kuminem. Popularna wegańska potrawa w krajach arabskich. Lubiana na całym świecie, szczególnie jako street food i roślinna alternatywa kebabu. Namoczoną ciecierzycę najlepiej zmiksować w melakserze. Idealny falafel jest z zewnątrz chrupiący, w środku natomiast miękki. Taki właśnie otrzymamy z poniższego przepisu.', 'falafel.jpg'),
       ('Hummus', 0L, 1L, 'Pasta z ugotowanej ciecierzy z sezamem i czosnkiem.', 'hummus.jpg'),
       ('Sajgonki', 0L, 2L, 'Można je przygotować z podsmażanego wcześniej mięsa (farszu) lub z surowego mięsa i surowych warzyw. Te drugie są oryginalnymi sajgonkami jak z wietnamskiej restauracji, tylko wymagają smażenia w głębszym tłuszczu i trochę dłużej. Natomiast sajgonki z gotowego farszu nieco ciężej się zwija a po usmażeniu farsz nie jest zbity tylko trochę sypki. Ich zaletą jest to, że wystarczy je tylko krótko obsmażyć.', 'spring-rolls.jpg'),
       ('Sushi', 0L, 2L, 'Potrawa japońska złożona z gotowanego ryżu zaprawionego octem ryżowym (su) oraz różnych dodatków w postaci, przeważnie surowych: owoców morza, wodorostów nori, kawałków ryb, warzyw, grzybów, a także omletu japońskiego (tamago-yaki), tofu, ziarna sezamowego (goma). Ze względu na bardzo krótki termin przydatności do spożycia, w restauracjach japońskich jest przygotowywana po dokonaniu zamówienia.', 'sushi.jpg'),
       ('Chili con carne', 0L, 3L, 'tradycyjna potrawa kuchni teksańskiej, spotykana często jako fastfood w amerykańskich barach. Główne składniki to: różnego rodzaju papryka chili, cebula, czosnek, pomidory i mielone lub drobno siekane mięso (zwykle wołowina, czasem spotyka się inne). Potrawę przyprawia się za pomocą kminu rzymskiego (kuminu) i pieprzu. Często dodaje się też inne składniki w tym ziarna fasoli i kukurydzy.', 'chili-con-carne.jpg'),
       ('Guacamole', 0L, 3L, 'Meksykański sos (salsa) przyrządzany na bazie awokado. Guacamole swoje początki miał już w czasach azteckich. Oprócz awokado dodaje się także limonkę i sól. Poszczególne rodzaje guacamole mogą zawierać pomidory, paprykę chili, cebulę, kolendrę, czosnek i inne przyprawy. Spożywa się go zazwyczaj z plackami tortilla, chociaż Meksykanie dodają go do niemal każdej przystawki.', 'guacamole.jpg');
